export const fields = [
  "Tên sản phẩm",
  "Mã SKU",
  "Mã BARCODE",
  "Theo dõi kho",
  "Danh mục",
  "Thuộc tính",
  "Có phân loại",
  "Phân loại chính",
  "Phân loại phụ",
  "DS phân loại",
  "Giá bán lẻ",
  "Giá nhập",
  "Hình ảnh",
  "Hoa hồng CTV (%)",
  "Xu cho đại lý",
  "Mô tả",
  "Nội dung cho CTV",
  "Trạng thái",
  "Tiêu đề SEO",
  "Miêu tả SEO",
];
